add accessors to cache objects
kirillseva/cacher pull request #16
Opened 2018-03-04 01:14 UTC by abelcastilloavant

Addresses https://github.com/kirillseva/cacher/issues/1

So yeah, overloading the `[[` operator is risky, but at least it's doable.

2018-03-04 01:30 UTC, abelcastilloavant commented
Well then - that broke a lot of tests.

2018-03-05 15:28 UTC, kirillseva requested changes
Please remove your vim swap files from the PR

2018-03-05 15:28 UTC, kirillseva commented on R/accessors.R
> +}
don't you need to export them?

2018-03-05 15:28 UTC, kirillseva commented on tests/testthat/test-accessors.R
> +})
It's great that tests work locally, but I'm pretty sure that those methods need to be `@export`'ed

2018-03-05 17:20 UTC, kirillseva approved these changes

2018-03-05 17:20 UTC, merged